services:
  glvd-postgres:
    image: ghcr.io/gardenlinux/glvd-postgres:2026.01.19
    hostname: glvd-postgres
    networks:
      - glvd
    volumes:
      - glvd_db_volume:/var/lib/postgresql
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glvd -d glvd"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s

  glvd-init:
    image: ghcr.io/gardenlinux/glvd-init:2026.01.19
    networks:
      - glvd
    depends_on:
      glvd-postgres:
        condition: service_healthy
        restart: false
    environment:
      PGHOST: glvd-postgres


  glvd:
    image: ghcr.io/gardenlinux/glvd-api:2026.01.19
    hostname: glvd
    networks:
      - glvd
    depends_on:
      glvd-postgres:
        condition: service_healthy
        restart: false
      glvd-init:
        condition: service_completed_successfully
        restart: false
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://glvd-postgres:5432/glvd"
      SPRING_DATASOURCE_USERNAME: "glvd"
      SPRING_DATASOURCE_PASSWORD: "glvd"
      SPRING_JPA_DATABASEPLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_BOOT_ALLOW_JDBC_METADATA_ACCESS: "false"
      SPRING_JPA_HIBERNATE_DDLAUTO: "none"
      SPRING_SQL_INIT_MODE: "never"
    ports:
      - "8080:8080"

networks:
  glvd: {}

volumes:
  glvd_db_volume:
