apiVersion: v1
kind: ConfigMap
metadata:
  name: glvd-ingestion
  namespace: glvd
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: glvd-ingestion
data:
  databaseName: glvd
  databaseHost: glvd-database-0.glvd-database
  databasePort: "5432"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glvd-changelogs-pvc
  namespace: glvd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: glvd-ingestion
  namespace: glvd
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: glvd-ingestion
spec:
  schedule: "30 8 * * 1-5"
  timeZone: "Europe/Berlin"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: glvd
        gardenlinux.io/glvd-component: glvd-ingestion
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: data-ingestion
            image: ghcr.io/gardenlinux/glvd-data-ingestion:latest
            # resources:
            #   requests:
            #     cpu: "1"
            #     memory: "2Gi"
            #   limits:
            #     cpu: "2"
            #     memory: "4Gi"
            command:
              - /bin/bash
              - -c
              - sleep 5 && echo start && python3 /usr/local/src/src/glvd/download_changelog_files.py && /usr/local/src/ingest-postgres.sh
            env:
              - name: PGDATABASE
                valueFrom:
                  configMapKeyRef:
                    name: glvd-ingestion
                    key: databaseName
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: username
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: password
              - name: PGHOST
                valueFrom:
                  configMapKeyRef:
                    name: glvd-ingestion
                    key: databaseHost
              - name: PGPORT
                valueFrom:
                  configMapKeyRef:
                    name: glvd-ingestion
                    key: databasePort
            volumeMounts:
              - name: changelogs
                mountPath: /changelogs
          volumes:
            - name: changelogs
              persistentVolumeClaim:
                claimName: glvd-changelogs-pvc
