apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert.gardener.cloud/purpose: managed
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: security.gardenlinux.org
    dns.gardener.cloud/ip-stack: dual-stack
    dns.gardener.cloud/ttl: "300"
  name: glvd
  namespace: glvd
spec:
  ingressClassName: nginx
  rules:
  - host: security.gardenlinux.org
    http:
      paths:
      - backend:
          service:
            name: glvd
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - security.gardenlinux.org
    secretName: security-gl-org
